name = "amazon-scrap"
type = "webpack"
account_id = "fdcbb0c94355aa3e140230a892ab92ed"
workers_dev = true
route = "https://www.amazon.in/*"
zone_id = "d7467b88596c68d9f5c59de1969bd331"
main = "src/index.ts"
compatibility_date = "2023-03-06"

